### ISSUE TITLE
In-game server selection?

### ISSUE THREAD

**Issue by FoxxMD** [BeatTogether/BeatTogether.UnifiedServer#4]
Hello! Looking forward to the unified server guide.

I was wondering if there will eventually be an in-game way to input `ApiUrl`? For quest users, especially those using one-click solutions like [ModsBeforeFriday](https://mbf.bsquest.xyz/), we don't get a chance to modify the mod before it is installed.

Thanks for the hard work on BeatTogether!

**Comment by Kevman95** [comment]
Hello,

We do not plan on providing a in game based editor to add servers at this time.

If you'd like to add servers as default, I'd suggest recompiling the PC or Quest mod with your custom server.  You also can just provide your configuration to others manually. 

Once added via the configuration file, you'll see it in the server selector list in game. I updated our readme about this: https://github.com/BeatTogether/BeatTogether.UnifiedServer?tab=readme-ov-file#beattogether-mod-configuration
